//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveApp.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveApp.Resources.Resource_en", typeof(Resource_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred:.
        /// </summary>
        internal static string AnErrorOccurred {
            get {
                return ResourceManager.GetString("An error occurred:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup deleted successfully..
        /// </summary>
        internal static string BackupDeletedSuccessfully {
            get {
                return ResourceManager.GetString("Backup deleted successfully.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup does not exist.
        /// </summary>
        internal static string BackupDoesNotExist {
            get {
                return ResourceManager.GetString("Backup does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup executed successfully.
        /// </summary>
        internal static string BackupExecutedSuccessfully {
            get {
                return ResourceManager.GetString("Backup executed successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Backup updated successfully..
        /// </summary>
        internal static string BackupUpdatedSuccessfully {
            get {
                return ResourceManager.GetString("Backup updated successfully.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Backup.
        /// </summary>
        internal static string ChangeBackup {
            get {
                return ResourceManager.GetString("Change Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        internal static string ChangeLanguage {
            get {
                return ResourceManager.GetString("Change Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose An Option.
        /// </summary>
        internal static string ChooseAnOption {
            get {
                return ResourceManager.GetString("Choose An Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the type of backup:.
        /// </summary>
        internal static string ChooseTheTypeOfBackup {
            get {
                return ResourceManager.GetString("Choose the type of backup:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Backup.
        /// </summary>
        internal static string CreateBackup {
            get {
                return ResourceManager.GetString("Create Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Multiple.
        /// </summary>
        internal static string CreateMultiple {
            get {
                return ResourceManager.GetString("Create Multiple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Multiple Backups:.
        /// </summary>
        internal static string CreateMultipleBackups {
            get {
                return ResourceManager.GetString("Create Multiple Backups:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Single.
        /// </summary>
        internal static string CreateSingle {
            get {
                return ResourceManager.GetString("Create Single", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Single Backup:.
        /// </summary>
        internal static string CreateSingleBackup {
            get {
                return ResourceManager.GetString("Create Single Backup:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Backup.
        /// </summary>
        internal static string DeleteBackup {
            get {
                return ResourceManager.GetString("Delete Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential.
        /// </summary>
        internal static string Differential {
            get {
                return ResourceManager.GetString("Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Differential Backup Method.
        /// </summary>
        internal static string DifferentialBackupMethod {
            get {
                return ResourceManager.GetString("Differential Backup Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter a name for the Backup (15 max).
        /// </summary>
        internal static string EnterANameForTheBackup {
            get {
                return ResourceManager.GetString("Enter a name for the Backup (15 max)", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the backup numbers to execute (e.g., '1', '1-3', '1;3':.
        /// </summary>
        internal static string EnterTheBackupNumbersToExecute {
            get {
                return ResourceManager.GetString("Enter the backup numbers to execute (e.g., '1', '1-3', '1;3'):", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Directory source for the backup.
        /// </summary>
        internal static string EnterTheDirectorySourceForTheBackup {
            get {
                return ResourceManager.GetString("Enter the Directory source for the backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Name of the backup that you want to delete:.
        /// </summary>
        internal static string EnterTheNameOfTheBackupThatYouWantToDelete {
            get {
                return ResourceManager.GetString("Enter the Name of the backup that you want to delete:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the Name of the backup that you want to modify:.
        /// </summary>
        internal static string EnterTheNameOfTheBackupThatYouWantToModify {
            get {
                return ResourceManager.GetString("Enter the Name of the backup that you want to modify:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter the new name for the backup:.
        /// </summary>
        internal static string EnterTheNewNameForTheBackup {
            get {
                return ResourceManager.GetString("Enter the new name for the backup:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Execute Backup.
        /// </summary>
        internal static string ExecuteBackup {
            get {
                return ResourceManager.GetString("Execute Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Full Backup Method.
        /// </summary>
        internal static string FullBackupMethod {
            get {
                return ResourceManager.GetString("Full Backup Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid choice.
        /// </summary>
        internal static string InvalidChoice {
            get {
                return ResourceManager.GetString("Invalid choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Option.
        /// </summary>
        internal static string InvalidOption {
            get {
                return ResourceManager.GetString("Invalid Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Language changed to.
        /// </summary>
        internal static string LanguageChangedTo {
            get {
                return ResourceManager.GetString("Language changed to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leave.
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MainMenuTitle {
            get {
                return ResourceManager.GetString("Main Menu Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name:.
        /// </summary>
        internal static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No backup numbers provided.
        /// </summary>
        internal static string NoBackupNumbersProvided {
            get {
                return ResourceManager.GetString("No backup numbers provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid backup numbers provided.
        /// </summary>
        internal static string NoValidBackupNumbersProvided {
            get {
                return ResourceManager.GetString("No valid backup numbers provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The backup was completed successfully!.
        /// </summary>
        internal static string TheBackupWasCompletedSuccessfully_ {
            get {
                return ResourceManager.GetString("The backup was completed successfully!", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The directory source doesn't exist.
        /// </summary>
        internal static string TheDirectorySourceDoesntExist {
            get {
                return ResourceManager.GetString("The directory source doesn't exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This name is not valid.
        /// </summary>
        internal static string ThisNameIsNotValid {
            get {
                return ResourceManager.GetString("This name is not valid", resourceCulture);
            }
        }
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changer de Langue.
        /// </summary>
        internal static string EnterANameForTheBackup15max {
            get
            {
                return ResourceManager.GetString("Enter a name for the Backup-15 max", resourceCulture);
            }
        }
    }
}
