//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasySaveApp_WPF.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource_fr {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource_fr() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasySaveApp.Resources.Resource_fr", typeof(Resource_fr).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Une erreur s&apos;est produite:.
        /// </summary>
        internal static string An_error_occurred_ {
            get {
                return ResourceManager.GetString("An error occurred:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde supprimée avec succès..
        /// </summary>
        internal static string Backup_deleted_successfully_ {
            get {
                return ResourceManager.GetString("Backup deleted successfully.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La sauvegarde n&apos;existe pas..
        /// </summary>
        internal static string Backup_does_not_exist {
            get {
                return ResourceManager.GetString("Backup does not exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde exécutée avec succès..
        /// </summary>
        internal static string Backup_executed_successfully {
            get {
                return ResourceManager.GetString("Backup executed successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Sauvegarde mise à jour avec succès..
        /// </summary>
        internal static string Backup_updated_successfully_ {
            get {
                return ResourceManager.GetString("Backup updated successfully.", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La sauvegarde a été effectuée avec succès !.
        /// </summary>
        internal static string backupSucess {
            get {
                return ResourceManager.GetString("backupSucess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Modifier un sauvegarde.
        /// </summary>
        internal static string Change_Backup {
            get {
                return ResourceManager.GetString("Change Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Changer de Langue.
        /// </summary>
        internal static string Change_Language {
            get {
                return ResourceManager.GetString("Change Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez une option.
        /// </summary>
        internal static string Choose_An_Option {
            get {
                return ResourceManager.GetString("Choose An Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choisissez le type de sauvegarde:.
        /// </summary>
        internal static string Choose_the_type_of_backup_ {
            get {
                return ResourceManager.GetString("Choose the type of backup:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Créer une sauvegarde.
        /// </summary>
        internal static string Create_Backup {
            get {
                return ResourceManager.GetString("Create Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Supprimer la sauvegarde.
        /// </summary>
        internal static string Delete_Backup {
            get {
                return ResourceManager.GetString("Delete Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Différentielle.
        /// </summary>
        internal static string Differential {
            get {
                return ResourceManager.GetString("Differential", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Méthode de sauvegarde.
        /// </summary>
        internal static string Differential_Backup_Method {
            get {
                return ResourceManager.GetString("Differential Backup Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez les numéros de sauvegarde à exécuter (e.g., &apos;1&apos;, &apos;1-3&apos;, &apos;1;3&apos;):.
        /// </summary>
        internal static string Enter_the_backup_numbers_to_execute__e_g____1____1_3____1_3___ {
            get {
                return ResourceManager.GetString("Enter the backup numbers to execute (e.g., \'1\', \'1-3\', \'1;3\'):", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez la source du répertoire pour la sauvegarde.
        /// </summary>
        internal static string Enter_the_Directory_source_for_the_backup {
            get {
                return ResourceManager.GetString("Enter the Directory source for the backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez le nom de la sauvegarde que vous souhaitez supprimer:.
        /// </summary>
        internal static string Enter_the_Name_of_the_backup_that_you_want_to_delete_ {
            get {
                return ResourceManager.GetString("Enter the Name of the backup that you want to delete:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez le nom de la sauvegarde que vous souhaitez modifier:.
        /// </summary>
        internal static string Enter_the_Name_of_the_backup_that_you_want_to_modify_ {
            get {
                return ResourceManager.GetString("Enter the Name of the backup that you want to modify:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Saisissez le nouveau nom de la sauvegarde:.
        /// </summary>
        internal static string Enter_the_new_name_for_the_backup_ {
            get {
                return ResourceManager.GetString("Enter the new name for the backup:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Entrez un nom pour la sauvegarde -15 max.
        /// </summary>
        internal static string EnterMax {
            get {
                return ResourceManager.GetString("EnterMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exécuter la sauvegarde.
        /// </summary>
        internal static string Execute_Backup {
            get {
                return ResourceManager.GetString("Execute Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Complète.
        /// </summary>
        internal static string Full {
            get {
                return ResourceManager.GetString("Full", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Méthode de sauvegarde complète.
        /// </summary>
        internal static string Full_Backup_Method {
            get {
                return ResourceManager.GetString("Full Backup Method", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choix invalide.
        /// </summary>
        internal static string Invalid_choice {
            get {
                return ResourceManager.GetString("Invalid choice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Option invalide.
        /// </summary>
        internal static string Invalid_Option {
            get {
                return ResourceManager.GetString("Invalid Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La langue a été modifiée en.
        /// </summary>
        internal static string Language_changed_to {
            get {
                return ResourceManager.GetString("Language changed to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Quitter.
        /// </summary>
        internal static string Leave {
            get {
                return ResourceManager.GetString("Leave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Menu.
        /// </summary>
        internal static string Main_Menu_Title {
            get {
                return ResourceManager.GetString("Main Menu Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nom:.
        /// </summary>
        internal static string Name_ {
            get {
                return ResourceManager.GetString("Name:", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun numéro de secours fourni..
        /// </summary>
        internal static string No_backup_numbers_provided {
            get {
                return ResourceManager.GetString("No backup numbers provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Aucun numéro de sauvegarde valide fourni..
        /// </summary>
        internal static string No_valid_backup_numbers_provided {
            get {
                return ResourceManager.GetString("No valid backup numbers provided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à La source du répertoire n&apos;existe pas.
        /// </summary>
        internal static string The_directory_source_doesn_t_exist {
            get {
                return ResourceManager.GetString("The directory source doesn\'t exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ce nom n&apos;est pas valide.
        /// </summary>
        internal static string This_name_is_not_valid {
            get {
                return ResourceManager.GetString("This name is not valid", resourceCulture);
            }
        }
    }
}
